### ISSUE TITLE
Ik zie socket.io code maar jullie importeren het nog niet.

### ISSUE THREAD

**Issue by ju5tu5** [Marwaxhello/connecting-people-realtime-web-app#1]
Jullie doen nog niet echt iets met sockets en misschien is het ook niet nodig voor jullie toepassing.. maar als jullie dat van plan zijn is het handig om in ieder geval `npm install socket.io` te gebruiken.

https://github.com/Marwaxhello/connecting-people-realtime-web-app/blob/ef32adcd8a318569841999289b209250a4755ef2/package.json#L29-L33C4

**Comment by Maaike0904** [comment]
Ik heb het geïnstalleerd 😄
